// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iytnmwhblsmqsnmipryl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml5dG5td2hibHNtcXNubWlwcnlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MTE4MDQsImV4cCI6MjA2MjM4NzgwNH0.H-WkzAPhjNh8gxCIS7-I6oH476UPk_DL8WwViWycI1s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);